bootstrap: Add code to pull in autoconf archive files.
darcs-hash:20061022080504-789c2-1432856d8aec82de3a9746a3b1adeba83bccff13.gz

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -59,6 +59,18 @@ if ! which autoreconf &> /dev/null; then
 	exit
 fi
 
+if ! test -e /usr/share/autoconf-archive/acx_pthread.m4; then
+	echo "*** Cannot find file '/usr/share/autoconf-archive/acx_pthread.m4'. ***"
+	exit
+fi
+
+#
+# Add autoconf archive files.
+#
+
+mkdir -p m4
+cp /usr/share/autoconf-archive/acx_pthread.m4 m4/.
+
 #
 # Make documentation
 #
