bootstrap: change autoconf-archive -> aclocal, according to recent Ubuntu convention.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -59,8 +59,8 @@ if ! which autoreconf &> /dev/null; then
 	exit
 fi
 
-if ! test -e /usr/share/autoconf-archive/acx_pthread.m4; then
-	echo "*** Cannot find file '/usr/share/autoconf-archive/acx_pthread.m4'. ***"
+if ! test -e /usr/share/aclocal/acx_pthread.m4; then
+	echo "*** Cannot find file '/usr/share/aclocal/acx_pthread.m4'. ***"
 	exit
 fi
 
@@ -69,7 +69,7 @@ fi
 #
 
 mkdir -p m4
-cp /usr/share/autoconf-archive/acx_pthread.m4 m4/.
+cp /usr/share/aclocal/acx_pthread.m4 m4/.
 
 #
 # Make documentation
